# Note 1:
# `conda activate <env>` fails with the following error: 
# "CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'."
# The current workaround is to use this command. 
# Source: ga(https://www.kangzhiq.com/2020/05/02/how-to-activate-a-conda-environment-in-a-remote-machine/)

name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Update conda and create environment
      run: |
        $CONDA/bin/conda --version
        $CONDA/bin/conda update -n base -c defaults conda
        $CONDA/bin/conda --version
        $CONDA/bin/conda env list
        $CONDA/bin/conda env update --file environment_platformless.yml --name pythontemplate2
        $CONDA/bin/conda env list
    - name: Test with pytest
      run: |
        eval "$($CONDA/bin/conda shell.bash hook)"  # See Note 1
        $CONDA/bin/conda activate pythontemplate2
        $CONDA/bin/conda env list
        $CONDA/bin/conda install pytest
        $CONDA/bin/pytest
        

        

