name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Update conda and create environment
      run: |
        conda info
        conda update -n base -c defaults conda
        conda info
        conda env list
        conda env update --file environment_platformless.yml --name pythontemplate2
        conda env list
    - name: Activate environment
      run: |
        eval "$(conda shell.bash hook)"
        conda activate pythontemplate2
        conda env list
    - name: Test with pytest
      run: |
        conda env list
        which pytest || echo pytest is not installed
        echo $CONDA/bin/pytest

        

