# Note 1:
# `conda activate <env>` fails with the following error: 
# "CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'."
# The current workaround is to use this command. 
# Source: (https://www.kangzhiq.com/2020/05/02/how-to-activate-a-conda-environment-in-a-remote-machine/)

name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Update conda and create environment
      run: |
        conda --version
        conda update -n base -c defaults conda
        conda --version
        conda env list
        conda env update --file environment_platformless.yml --name pythontemplate2
        conda env list
    - name: Test with pytest
      run: |
        eval "$(conda shell.bash hook)"  # See Note 1
        conda env list
        conda activate pythontemplate2
        conda env list
        conda --version
        conda install pytest
        pytest
        

        

