name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies using miniconda
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda update -n base -c defaults conda   # update conda first
        $CONDA/bin/conda env update --file environment_platformless.yml --name pythontemplate2
        $CONDA/bin/conda activate pythontemplate2
    - name: Test with pytest
      run: |
        conda install pytest
        $CONDA/bin/pytest