name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        conda update -n base -c defaults conda  #update conda
        #$CONDA/bin/conda env create -f environment2.yml
        $CONDA/bin/conda env update --file environment2.yml --name pythontemplate2
