# Note 1:
# `conda activate <env>` fails with the following error: 
# "CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'."
# The current workaround is to use this command. 
# Source: (https://www.kangzhiq.com/2020/05/02/how-to-activate-a-conda-environment-in-a-remote-machine/)

name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Update conda and create environment from file
      run: |
        conda --version
        conda update -n base -c defaults conda
        conda --version
        conda env list
        conda env update --file environment_platformless.yml --name pythontemplate2
        conda env list
    - name: Lint with flake8
      run: |
        conda install flake8
        which flake8 || echo flake8 is not available in the path
        $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Activate environment and test with pytest
      run: |
        eval "$(conda shell.bash hook)"  # See Note 1
        conda env list
        conda activate pythontemplate2
        conda env list
        conda install pytest
        pytest
        

        

