name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Update conda and install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda update -n base -c defaults conda   # update conda first
        $CONDA/bin/conda env update --file environment_platformless.yml --name pythontemplate2
    - name: Activate environment
      run: |g
        eval "$(conda shell.bash hook)"
        $CONDA/bin/conda activate pythontemplate2

