name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Update conda and install dependencies
      run: |
        conda update -n base -c defaults conda
        conda env update --file environment_platformless.yml --name pythontemplate2
    - name: Activate environment
      run: |
        eval "$(conda shell.bash hook)"
        conda activate

